version: '3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: concess-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - "concessionaria:/var/lib/mysql"
      - "./initial_concessionaria:/docker-entrypoint-initdb.d"

volumes:
  concessionaria: